#!/bin/bash
# Build and install a native macOS .app wrapper for the dashboard.
# Idempotent — re-run any time to rebuild the bundle.
#
# Env overrides (all optional):
#   APP_NAME       display name of the app                        (default: "Routines Dashboard")
#   APP_ID         reverse-DNS bundle identifier                  (default: com.local.routines-dashboard)
#   INSTALL_DIR    where to place the .app                        (default: /Applications)
#   PROJECT_DIR    path to this repo's checkout                    (default: git toplevel of this script)
#   PORTLESS_NAME  hostname stem for portless registration         (default: routines)
#   URL            full URL the webview should load                (default: https://<PORTLESS_NAME>.localhost)
#
# Usage:
#   ./scripts/install-mac-app.sh
#   APP_NAME="My Routines" URL=http://localhost:3000 ./scripts/install-mac-app.sh
#
# Requires: swiftc (Xcode Command Line Tools), sips, iconutil, plutil.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

APP_NAME="${APP_NAME:-Routines Dashboard}"
APP_ID="${APP_ID:-com.local.routines-dashboard}"
INSTALL_DIR="${INSTALL_DIR:-/Applications}"
PROJECT_DIR="${PROJECT_DIR:-$REPO_DIR}"
PORTLESS_NAME="${PORTLESS_NAME:-routines}"
URL="${URL:-https://${PORTLESS_NAME}.localhost}"

APP_BUNDLE="$INSTALL_DIR/$APP_NAME.app"
CONTENTS="$APP_BUNDLE/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RES_DIR="$CONTENTS/Resources"
LAUNCHER="$MACOS_DIR/launcher"
WEBVIEW_BIN="$MACOS_DIR/webview"

require() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1" >&2; exit 1; }; }
require swiftc
require sips
require iconutil
require plutil

echo "==> installing to $APP_BUNDLE"
mkdir -p "$MACOS_DIR" "$RES_DIR"

# ---------- Info.plist ----------
cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>$APP_ID</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleSignature</key><string>????</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST
plutil -lint "$CONTENTS/Info.plist" >/dev/null

# ---------- Launcher ----------
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/bash
# Auto-generated by scripts/install-mac-app.sh. Regenerate to change paths.
set -u

PROJECT_DIR="$PROJECT_DIR"
PORTLESS_NAME="$PORTLESS_NAME"
URL="$URL"

LOG_DIR="\$HOME/Library/Logs"
LOG="\$LOG_DIR/${APP_ID}.log"
mkdir -p "\$LOG_DIR"
log() { echo "[\$(date '+%Y-%m-%d %H:%M:%S')] \$*" >> "\$LOG"; }

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$HOME/bin:\$PATH"
if [ -s "\$HOME/.nvm/nvm.sh" ]; then . "\$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true; fi

WEBVIEW_BIN="\$(dirname "\$0")/webview"
launch_window() { log "launching webview"; exec "\$WEBVIEW_BIN"; }

server_up() {
  /usr/bin/curl -sk --max-time 3 -o /dev/null -w '%{http_code}' "\$URL" \\
    | grep -qE '^(200|3..)\$'
}

if server_up; then log "server up"; launch_window; fi

if [ ! -d "\$PROJECT_DIR/.next" ]; then
  log "no .next build — running pnpm build"
  ( cd "\$PROJECT_DIR" && pnpm build ) >> "\$LOG" 2>&1 || {
    log "pnpm build failed"
    /usr/bin/osascript -e "display notification \"Build failed — see \$LOG\" with title \"$APP_NAME\""
    exit 1
  }
fi

log "starting: portless \$PORTLESS_NAME -- pnpm start"
cd "\$PROJECT_DIR" || exit 1
if command -v portless >/dev/null 2>&1; then
  nohup portless "\$PORTLESS_NAME" -- pnpm start >> "\$LOG" 2>&1 &
else
  nohup pnpm start >> "\$LOG" 2>&1 &
fi

for _ in \$(seq 1 30); do
  if server_up; then log "server ready"; launch_window; fi
  sleep 1
done

log "server did not become ready in 30s — opening window with retry page"
launch_window
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# ---------- Swift WKWebView binary ----------
SWIFT_SRC="$RES_DIR/main.swift"
cat > "$SWIFT_SRC" <<SWIFT
import Cocoa
import WebKit

let URL_STRING = "$URL"
let APP_TITLE  = "$APP_NAME"

class AppDelegate: NSObject, NSApplicationDelegate, WKNavigationDelegate {
    var window: NSWindow!
    var webView: WKWebView!

    func applicationDidFinishLaunching(_ notification: Notification) {
        let contentRect = NSRect(x: 0, y: 0, width: 1280, height: 800)
        window = NSWindow(
            contentRect: contentRect,
            styleMask: [.titled, .closable, .miniaturizable, .resizable, .fullSizeContentView],
            backing: .buffered, defer: false
        )
        window.title = APP_TITLE
        window.center()
        window.setFrameAutosaveName("\(APP_TITLE)-MainWindow")
        window.tabbingMode = .disallowed

        let config = WKWebViewConfiguration()
        config.websiteDataStore = .default()
        webView = WKWebView(frame: contentRect, configuration: config)
        webView.autoresizingMask = [.width, .height]
        webView.navigationDelegate = self
        webView.allowsBackForwardNavigationGestures = true
        window.contentView = webView

        if let url = URL(string: URL_STRING) {
            webView.load(URLRequest(url: url))
        }
        window.makeKeyAndOrderFront(nil)
        NSApp.activate(ignoringOtherApps: true)
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool { true }

    // Accept self-signed / .localhost certs (portless dev).
    func webView(_ webView: WKWebView,
                 didReceive challenge: URLAuthenticationChallenge,
                 completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust,
           let trust = challenge.protectionSpace.serverTrust {
            completionHandler(.useCredential, URLCredential(trust: trust))
        } else {
            completionHandler(.performDefaultHandling, nil)
        }
    }

    func webView(_ w: WKWebView, didFail n: WKNavigation!, withError e: Error) { showRetry(e) }
    func webView(_ w: WKWebView, didFailProvisionalNavigation n: WKNavigation!, withError e: Error) { showRetry(e) }

    func showRetry(_ error: Error) {
        let html = """
        <html><body style="background:#0b0b0b;color:#e5e5e5;font-family:-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;">
        <div style="text-align:center;max-width:520px;padding:32px;">
          <h1 style="font-size:20px;margin:0 0 12px;">Dashboard server not reachable</h1>
          <p style="color:#999;margin:0 0 20px;font-size:14px;">\(error.localizedDescription)</p>
          <p style="color:#999;margin:0 0 20px;font-size:13px;">Expected: <code style="background:#222;padding:2px 6px;border-radius:4px;">\(URL_STRING)</code></p>
          <button onclick="location.reload()" style="background:#0070f3;color:white;border:none;padding:10px 20px;border-radius:6px;font-size:14px;cursor:pointer;">Retry</button>
        </div></body></html>
        """
        webView.loadHTMLString(html, baseURL: nil)
    }
}

let app = NSApplication.shared
let delegate = AppDelegate()
app.delegate = delegate
app.setActivationPolicy(.regular)
app.run()
SWIFT

echo "==> compiling WKWebView binary"
swiftc -O -target arm64-apple-macos11.0 -o "$WEBVIEW_BIN" "$SWIFT_SRC"

# ---------- Icon ----------
FAVICON="$REPO_DIR/src/app/favicon.ico"
if [ -f "$FAVICON" ]; then
  echo "==> building AppIcon.icns from favicon"
  TMP=$(mktemp -d); ICONSET="$TMP/AppIcon.iconset"; mkdir -p "$ICONSET"
  sips -s format png "$FAVICON" --out "$TMP/base.png" >/dev/null 2>&1 || true
  sips -Z 1024 "$TMP/base.png" --out "$TMP/base-1024.png" >/dev/null 2>&1 || true
  if [ -f "$TMP/base-1024.png" ]; then
    for sz in 16 32 64 128 256 512 1024; do
      sips -Z $sz "$TMP/base-1024.png" --out "$ICONSET/icon_${sz}x${sz}.png" >/dev/null
    done
    for sz in 16 32 128 256 512; do
      cp "$ICONSET/icon_$((sz*2))x$((sz*2)).png" "$ICONSET/icon_${sz}x${sz}@2x.png"
    done
    iconutil -c icns "$ICONSET" -o "$RES_DIR/AppIcon.icns"
  else
    echo "   (skipped — could not convert favicon)"
  fi
  rm -rf "$TMP"
fi

# ---------- Refresh Launch Services ----------
touch "$APP_BUNDLE"
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister \
  -f "$APP_BUNDLE" >/dev/null 2>&1 || true

echo ""
echo "==> done"
echo "    bundle: $APP_BUNDLE"
echo "    url:    $URL"
echo "    log:    ~/Library/Logs/${APP_ID}.log"
echo ""
echo "Launch: open \"$APP_BUNDLE\""
